# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180223_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gradute_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_join_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_belong',
        ),
        migrations.RemoveField(
            model_name='user',
            name='xue_li',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zhengzhi_mianmao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zhengzhi_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='job_time',
            field=models.CharField(default='0001', max_length=10),
        ),
    ]
